INSERT INTO Account (username, password) VALUES ('imallinson', 'password')
INSERT INTO Ingredient (ingredientName, amount, measurement, username) VALUES ('Beef Mince', 250, 'g', 'imallinson')
INSERT INTO Ingredient (ingredientName, amount, measurement, username) VALUES ('Onions', 1, '', 'imallinson')
INSERT INTO Ingredient (ingredientName, amount, measurement, username) VALUES ('Garlic', 1, 'clove', 'imallinson')
INSERT INTO Ingredient (ingredientName, amount, measurement, username) VALUES ('Passata', 250, 'ml', 'imallinson')
INSERT INTO Ingredient (ingredientName, amount, measurement, username) VALUES ('Spaghetti', 150, 'g', 'imallinson')
INSERT INTO Ingredient (ingredientName, amount, measurement, username) VALUES ('Dried Basil', 1, 'tsp', 'imallinson')
INSERT INTO Ingredient (ingredientName, amount, measurement, username) VALUES ('Dried Oregano', 1, 'tsp', 'imallinson')
INSERT INTO Ingredient (ingredientName, amount, measurement, username) VALUES ('Parmesan', 25, 'g', 'imallinson')